# Generated by Django 2.0 on 2017-12-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentSender', models.CharField(max_length=10)),
                ('commentSubject', models.CharField(max_length=20)),
                ('commentMessage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employeeName', models.CharField(max_length=20)),
                ('employeeId', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('employeeTenure', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField(max_length=2)),
                ('taskName', models.CharField(max_length=20)),
                ('taskResourceRequired', models.IntegerField(max_length=2)),
                ('taskRequester', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='teams',
            new_name='team',
        ),
        migrations.AddField(
            model_name='task',
            name='taskTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamtask', to='dashservice.team'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammember', to='dashservice.team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamcomments', to='dashservice.team'),
        ),
    ]
