# Generated by Django 2.0 on 2017-12-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashservice', '0002_auto_20171225_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeTenure',
            field=models.IntegerField(),
        ),
    ]
